### PR TITLE
Reorg to cause 'npm i git:' commands to work

### PR DESCRIPTION
**Pull request by robinbb**
The package.json file must be in the root directory of repositories
containining npm packages. Otherwise, npm package specifiers beginning with
'git' will not work. This commit reorganizes the repo structure to one with
package.json in the root.

### CODE REVIEW

**Comment by KevinGrandon** [comment]
Thanks for the pull request! I definitely want to get git:// urls working. I'm also experimenting with having another package.json in the root folder, similar to what babel does. I'll do some testing this weekend on both approaches.

**Comment by KevinGrandon** [comment]
@robinbb Hey Robin, thanks again for the contribution here. For the time being I want to minimize the changes, so I've added a package.json in the root, which will shell out to the core library, and allow git:// urls to work in package.json. You can find the package.json here: https://github.com/KevinGrandon/ghostjs/blob/master/package.json

Please let me know how this works for you and if it resolves the git:// url problem. Also file an issue if you have any change requests to this library, I'm trying to make this better all the time.

**Comment by robinbb** [comment]
This won't work. It will create a 'ghostjs-core/node_modules' directory, but it will not install the dependencies of ghostjs in whatever package has ghostjs as a dependency, for example.

**Comment by robinbb** [comment]
FYI, in my repo, I have updated dependencies and added support for HTTPS websites (with PhantomJS as a driver, only). Testing for HTTPS support is also there. Unfortunately, all of that work is built upon my reorg. Feel free to take my changes.

**Comment by KevinGrandon** [comment]
Nice, I'll upstream it!

In package.json, we now do: `(cd ghostjs-core && npm install)`. This should install the dependencies when installed as a git:// url. I'm seeing all dependencies being installed in my testing, but I'll test again later today. I definitely want that to work.

**Comment by KevinGrandon** [comment]
FYI - I've upstreamed commits into the core, and left you as the author - hope that's ok, if not let me know and I can change it.

Updating deps: https://github.com/KevinGrandon/ghostjs/commit/7d8ebfd4dcc8963309ac220eacd91ad01b201069
HTTPS option support: https://github.com/KevinGrandon/ghostjs/commit/ed61c60cfac34b2f387625d638eec75f9d8f9ddf

**Pull request closed without merging**
