### PR TITLE
Reorg to cause 'npm i git:' commands to work

### PR DESCRIPTION
**Pull request by robinbb**
The package.json file must be in the root directory of repositories
containining npm packages. Otherwise, npm package specifiers beginning with
'git' will not work. This changeset reorganizes the repo structure to one
with package.json in the root.

### CODE REVIEW

**Comment by KevinGrandon** [comment]
Thanks for the pull request, I'm not sure how necessary this is though. The idea was to potentially to follow the babel mono-repo approach here: https://github.com/babel/babel/tree/master/packages

Though thinking about this, I don't see us adding many more packages so maybe it makes sense to bring everything up to the root level.

**Comment by robinbb** [comment]
Kevin, thanks for looking. I have retracted (closed) this PR. I am currently working on a slightly improved reorg. I will point you to it (opening another PR) when it is ready, and you can decide then whether you want to move things to the root level.

Thanks for this open source package, BTW!

**Comment by KevinGrandon** [comment]
Sure thing. Can I ask what difficulties you're facing with the current structure? Are you having trouble with including this package in a larger project? Hacking on the ghostjs codebase? Something else?

**Comment by robinbb** [comment]
Yes, I needed to provide a change to the code (I will submit PR for that, too). And, before you publish the change to NPM, I need to provide the change to my colleagues. I wanted to provide it to them by simply putting my changed repo on Github, and then using a "git:" URL in our package.json instead of simply "ghost@1.1.7". Unfortunately, such "git:" URLs do not allow for the package.json file to be in a subdirectory.

**Comment by KevinGrandon** [comment]
Thanks. Filed an issue to track this work, happy to accept any PRs that keep everything working.

**Pull request closed without merging**
